services:
  backend:
    build:
      context: ./backend
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      JOB_URL_CONCURRENCY_LIMIT: 5
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
